name = "darma"
main = "worker.js"
compatibility_date = "2026-08-11"

[assets]
directory = "./public"
binding = "ASSETS"

# WAJIB: ganti dengan database_id dari perintah `npx wrangler d1 create darma`.
[[d1_databases]]
binding = "DB"
database_name = "darma"
database_id = "26ec49cb-4cd3-4f79-ad23-d2d7681d9423"
